version: '3'

services:

  nginx:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    image: ahmedadil098/nginximages:999
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    image: ahmedadil098/phpimages:999
    working_dir: /var/www/php
    volumes:
      - ./src:/var/www/php
    depends_on:
      - mysql

  mysql:
    build:
      context: ./.docker/mysql
      dockerfile: Dockerfile
    image: ahmedadil098/mysqlimages:999   # ✅ changed
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: demo
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - faisal-db-data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

  phpmyadmin:
    build:
      context: ./.docker/phpmyadmin
      dockerfile: Dockerfile
    image: ahmedadil098/myadminimages:999  # ✅ changed
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      PMA_HOST: mysql
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - mysql

volumes:
  faisal-db-data:
