name: LEMP Server
on:
  push:
    branches: [ src ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker Images
        run: |
         docker-compose up -d
         docker ps -a
        
